AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: surf-bot - a slack bot to check the surf

Outputs:
  AccountId:
    Value: !Ref AWS::AccountId
  StackId:
    Value: !Ref AWS::StackId
  StackName:
    Value: !Ref AWS::StackName
  Region:
    Value: !Ref AWS::Region

Resources:

  AuthOauth:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app/handlers/slack_handlers.oauth
      Runtime: nodejs6.10
      CodeUri: ./package/surf-bot.zip
      Environment:
        Variables:
          SLACK_OAUTH_ENDPOINT: SLACK_OAUTH_ENDPOINT
          SLACK_CLIENT_ID: SLACK_CLIENT_ID
          SLACK_CLIENT_SECRET: SLACK_CLIENT_SECRET
      Events:
        GetOauth:
          Type: Api
          Properties:
            Method: GET
            Path: /oauth

  SurfReport:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app/handlers/surfline_handlers.report
      Runtime: nodejs6.10
      CodeUri: ./package/surf-bot.zip
      Environment:
        Variables:
          SURFLINE_BASE_URL: SURFLINE_BASE_URL
      Events:
        PostSurfReport:
          Type: Api
          Properties:
            Method: POST
            Path: /surf
        GetSurfReport:
          Type: Api
          Properties:
            Method: GET
            Path: /surf
